export const REQUEST_GAMES = 'REQUEST_GAMES'
export const RECEIVE_GAMES = 'RECEIVE_GAMES'

export const REQUEST_MEDIA_URL = 'REQUEST_MEDIA_URL'
export const RECEIVE_MEDIA_URL = 'RECEIVE_MEDIA_URL'

export const ASK_LOGIN = 'ASK_LOGIN'
export const REQUEST_USER_TOKEN = 'REQUEST_USER_TOKEN'
export const RECEIVE_USER_TOKEN = 'RECEIVE_USER_TOKEN'