const teamsImages = {
  'njd': require('../img/njd.png'),
  'nyi': require('../img/nyi.png'),
  'nyr': require('../img/nyr.png'),
  'phi': require('../img/phi.png'),
  'pit': require('../img/pit.png'),
  'bos': require('../img/bos.png'),
  'buf': require('../img/buf.png'),
  'mtl': require('../img/mtl.png'),
  'ott': require('../img/ott.png'),
  'tor': require('../img/tor.png'),
  'car': require('../img/car.png'),
  'fla': require('../img/fla.png'),
  'tbl': require('../img/tbl.png'),
  'wsh': require('../img/wsh.png'),
  'chi': require('../img/chi.png'),
  'det': require('../img/det.png'),
  'nsh': require('../img/nsh.png'),
  'stl': require('../img/stl.png'),
  'cgy': require('../img/cgy.png'),
  'col': require('../img/col.png'),
  'edm': require('../img/edm.png'),
  'van': require('../img/van.png'),
  'ana': require('../img/ana.png'),
  'dal': require('../img/dal.png'),
  'lak': require('../img/lak.png'),
  'sjs': require('../img/sjs.png'),
  'cbj': require('../img/cbj.png'),
  'min': require('../img/min.png'),
  'wpg': require('../img/wpg.png'),
  'ari': require('../img/ari.png'),
}

export default teamsImages