# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nhl4chromecast' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nhl4chromecast
  pod 'google-cast-sdk'

end
